export const  YEAR_OPTIONS = [
  {value: "2024"},
  {value: "2023"},
  {value: "2022"},
  {value: "2021"},
  {value: "2020"},
  {value: "2019"},
  {value: "2018"},
  {value: "2017"},
  {value: "2016"},
  {value: "2023-2024"},
  {value: "2022-2023"},
  {value: "2021-2022"},
  {value: "2020-2022"},
  {value: "2019-2020"},
  {value: "2010-2020"},
  {value: "2010-2015"},
  {value: "2000-2010"},
  {value: "1990-2000"},
  {value: "1980-1990"},
];

export const COUTRY_OPTIONS = [
  {value: "Австралия"},
  {value: "Аргентина"},
  {value: "Армения"},
  {value: "Беларусь"},
  {value: "Бельгия"},
  {value: "Бразилия"},
  {value: "Великобритания"},
  {value: "Венгрия"},
  {value: "Германия"},
  {value: "Гонконг"},
  {value: "Дания"},
  {value: "Индия"},
  {value: "Ирландия"},
  {value: "Испания"},
  {value: "Италия"},
  {value: "Казахстан"},
  {value: "Канада"},
  {value: "Китай"},
  {value: "Колумбия"},
  {value: "Мексика"},
  {value: "Нидерланды"},
  {value: "Новая Зеландия"},
  {value: "Норвегия"},
  {value: "Польша"},
  {value: "Россия"},
  {value: "СССР"},
  {value: "США"},
  {value: "Таиланд"},
  {value: "Турция"},
  {value: "Финляндия"},
  {value: "Франция"},
  {value: "Швейцария"},
  {value: "Швеция"},
  {value: "ЮАР"},
  {value: "Южная Корея"},
  {value: "Япония"},
];

export const AGE_OPTIONS = [
  {value: "0"},
  {value: "6"},
  {value: "12"},
  {value: "14"},
  {value: "16"},
  {value: "18"},
];